persistence true
persistence_location /mosquitto/data/
log_dest stdout
log_type all

# Port 9081
listener 9081 0.0.0.0
allow_anonymous false

# Password file for authentication
password_file /mosquitto/config/passwd

# TLS disabled for now as server.key is missing
# cafile /mosquitto/config/certs/ca.crt
# certfile /mosquitto/config/certs/server.crt
# keyfile /mosquitto/config/certs/server.key
# tls_version tlsv1.2

# Necessary for eStation MQTT v5 stability
max_topic_alias 65535
max_packet_size 1048576
