# Generated by Django 6.0.1 on 2026-01-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_product_unique_together_alter_product_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='esltag',
            name='tag_image',
            field=models.ImageField(blank=True, null=True, upload_to='tag_designs/'),
        ),
        migrations.AlterField(
            model_name='esltag',
            name='tag_mac',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
