# Generated by Django 6.0.1 on 2026-01-28 21:22

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_esltag_tag_image_alter_esltag_tag_mac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esltag',
            name='tag_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.get_tag_path),
        ),
    ]
