# Generated by Django 6.0.1 on 2026-01-29 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_company_options_esltag_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esltag',
            name='paired_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='esl_tags', to='core.product'),
        ),
    ]
