# Generated by Django 6.0.1 on 2026-01-29 22:01

import core.models
import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_esltag_tag_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esltag',
            name='tag_image',
            field=models.ImageField(blank=True, null=True, storage=core.storage.OverwriteStorage(), upload_to=core.models.get_tag_path),
        ),
    ]
