# Generated by Django 5.1.5 on 2026-02-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_company_contact_email_company_mailing_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Global Admin'), ('owner', 'Company Owner'), ('manager', 'Store Manager'), ('readonly', 'Read-Only User')], default='admin', max_length=20),
        ),
    ]
