# Generated by Django 5.1.5 on 2026-02-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='esltag',
            name='color_type',
            field=models.CharField(blank=True, choices=[('BW', 'B&W'), ('BWR', 'BWR'), ('BWRY', 'BWRY')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='esltag',
            name='display_type',
            field=models.CharField(blank=True, default='E-Ink', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='esltag',
            name='height_px',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='esltag',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='esltag',
            name='width_px',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
