# Generated by Django 5.1.5 on 2026-02-05 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_esltag_color_type_esltag_display_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagHardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.CharField(help_text='e.g., ET0290-85', max_length=100, unique=True)),
                ('width_px', models.IntegerField(help_text='Width in pixels')),
                ('height_px', models.IntegerField(help_text='Height in pixels')),
                ('color_scheme', models.CharField(choices=[('BW', 'B&W'), ('BWR', 'BWR'), ('BWRY', 'BWRY')], default='BWRY', max_length=10)),
                ('display_size_inch', models.DecimalField(decimal_places=2, help_text='e.g., 2.90', max_digits=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='esltag',
            name='color_type',
        ),
        migrations.RemoveField(
            model_name='esltag',
            name='display_type',
        ),
        migrations.RemoveField(
            model_name='esltag',
            name='height_px',
        ),
        migrations.RemoveField(
            model_name='esltag',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='esltag',
            name='width_px',
        ),
        migrations.AddField(
            model_name='esltag',
            name='aisle',
            field=models.CharField(blank=True, help_text='e.g., Aisle 4', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='esltag',
            name='section',
            field=models.CharField(blank=True, help_text='e.g., Dairy', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='esltag',
            name='shelf_row',
            field=models.CharField(blank=True, help_text='e.g., Row 2', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_on_special',
            field=models.BooleanField(default=False, verbose_name='On Special / Promotion'),
        ),
        migrations.AddField(
            model_name='esltag',
            name='hardware_spec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.taghardware'),
        ),
    ]
