# Generated by Django 5.1.5 on 2026-02-08 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_taghardware_remove_esltag_color_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esltag',
            name='hardware_spec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.taghardware'),
        ),
    ]
