# Generated by Django 5.1.5 on 2026-02-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_esltag_hardware_spec'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='gateway_mac',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
