# Generated by Django 5.1.5 on 2026-02-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_last_seen_esltag_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esltag',
            name='aisle',
            field=models.CharField(blank=True, help_text='e.g., Aisle 4', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='esltag',
            name='section',
            field=models.CharField(blank=True, help_text='e.g., Dairy', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='esltag',
            name='shelf_row',
            field=models.CharField(blank=True, help_text='e.g., Row 2', max_length=20, null=True),
        ),
    ]
