# Generated by Django 5.1.5 on 2026-02-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_esltag_aisle_alter_esltag_section_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='esltag',
            options={'verbose_name': 'ESL Tag', 'verbose_name_plural': 'ESL Tags'},
        ),
        migrations.AddField(
            model_name='esltag',
            name='last_image_gen_success',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Successful Image Sync'),
        ),
        migrations.AddField(
            model_name='esltag',
            name='last_image_task_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Task ID'),
        ),
        migrations.AlterField(
            model_name='esltag',
            name='tag_mac',
            field=models.CharField(max_length=50, unique=True, verbose_name='Tag ID/MAC'),
        ),
    ]
