# Generated by Django 5.1.5 on 2026-02-21 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_esltag_options_esltag_last_image_gen_success_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esltag',
            name='tag_mac',
            field=models.CharField(max_length=50, unique=True, verbose_name='Tag ID/MAC'),
        ),
    ]
