# Generated by Django 5.1.5 on 2026-02-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_esltag_tag_mac'),
    ]

    operations = [
        migrations.AddField(
            model_name='esltag',
            name='last_image_task_token',
            field=models.IntegerField(blank=True, null=True, verbose_name='Task Token (1-255)'),
        ),
        migrations.AddField(
            model_name='esltag',
            name='sync_state',
            field=models.CharField(choices=[('IDLE', 'No Pending Tasks'), ('PENDING', 'Syncing to Tag...'), ('SUCCESS', 'Update Confirmed'), ('FAILED', 'Transmission Failed')], default='IDLE', max_length=20, verbose_name='Sync Status'),
        ),
        migrations.AddField(
            model_name='gateway',
            name='estation_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
