# Generated by Django 5.1.5 on 2026-02-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_esltag_last_image_task_token_esltag_sync_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esltag',
            name='sync_state',
            field=models.CharField(choices=[('IDLE', 'No Pending Tasks'), ('IMAGE_READY', 'Image Ready'), ('PENDING', 'Syncing to Tag...'), ('PUSHED', 'Pushed to MQTT'), ('RETRY_PENDING', 'MQTT Push failed, Retry Pending'), ('SUCCESS', 'Update Confirmed'), ('FAILED', 'Transmission Failed')], default='IDLE', max_length=20, verbose_name='Sync Status'),
        ),
    ]
