# Generated by Django 5.1.5 on 2026-02-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_esltag_sync_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esltag',
            name='sync_state',
            field=models.CharField(choices=[('IDLE', 'No Pending Tasks'), ('PROCESSING', 'Generating Image...'), ('IMAGE_READY', 'Image Prepared'), ('PUSHED', 'Sent to Gateway'), ('SUCCESS', 'Update Confirmed'), ('GEN_FAILED', 'Image Generation Failed'), ('PUSH_FAILED', 'Gateway Delivery Failed'), ('FAILED', 'General Failure')], default='IDLE', max_length=20, verbose_name='Sync Status'),
        ),
    ]
