# Generated by Django 5.1.5 on 2026-02-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_esltag_sync_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='esltag',
            name='template_id',
            field=models.IntegerField(choices=[(1, 'Standard Split (V1)'), (2, 'High-Visibility Promo (V2)')], default=1, help_text='Visual layout style for this tag.'),
        ),
    ]
