# Generated by Django 5.1.5 on 2026-02-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_esltag_template_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esltag',
            name='template_id',
            field=models.IntegerField(choices=[(1, 'Standard Split (V1)'), (2, 'High-Visibility Promo (V2)'), (3, 'Modern (V3)')], default=1, help_text='Visual layout style for this tag.'),
        ),
    ]
