# Generated by Django 5.1.5 on 2026-03-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_supplier_product_preferred_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='abbreviation',
            field=models.CharField(help_text='3 character code (e.g., GSC,STM,GHR,GAM)', max_length=3, unique=True),
        ),
    ]
