# Generated by Django 5.1.5 on 2026-03-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_alter_supplier_abbreviation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="esltag",
            name="aisle",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="esltag",
            name="last_image_gen_success",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="esltag",
            name="last_image_task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="esltag",
            name="last_image_task_token",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="esltag",
            name="section",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="esltag",
            name="shelf_row",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="esltag",
            name="sync_state",
            field=models.CharField(
                choices=[
                    ("IDLE", "No Pending Tasks"),
                    ("PROCESSING", "Generating Image..."),
                    ("IMAGE_READY", "Image Prepared"),
                    ("PUSHED", "Sent to Gateway"),
                    ("SUCCESS", "Update Confirmed"),
                    ("GEN_FAILED", "Image Generation Failed"),
                    ("PUSH_FAILED", "Gateway Delivery Failed"),
                    ("FAILED", "General Failure"),
                ],
                default="IDLE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="esltag",
            name="template_id",
            field=models.IntegerField(
                choices=[(1, "Standard (V1)"), (2, "Promo (V2)"), (3, "Modern (V3)")],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="abbreviation",
            field=models.CharField(
                help_text="3 character code (e.g., GSC, STM)", max_length=3, unique=True
            ),
        ),
    ]
