# Generated by Django 5.1.5 on 2026-03-07 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_alter_esltag_aisle_and_more"),
    ]

    def populate_store(apps, schema_editor):
        ESLTag = apps.get_model('core', 'ESLTag')
        for tag in ESLTag.objects.all():
            if tag.gateway:
                tag.store = tag.gateway.store
                tag.save()

    operations = [
        migrations.AddField(
            model_name="esltag",
            name="store",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="esl_tags",
                to="core.store",
            ),
        ),
        migrations.RunPython(populate_store),
        migrations.AlterField(
            model_name="esltag",
            name="tag_mac",
            field=models.CharField(max_length=50, verbose_name="Tag ID/MAC"),
        ),
        migrations.AlterUniqueTogether(
            name="esltag",
            unique_together={("tag_mac", "store")},
        ),
    ]
