# Generated by Django 5.1.5 on 2026-03-07 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_esltag_store_alter_esltag_tag_mac_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="esltag",
            name="last_successful_gateway_id",
            field=models.CharField(
                blank=True,
                max_length=4,
                null=True,
                verbose_name="Last Successful Gateway ID",
            ),
        ),
        migrations.AddField(
            model_name="gateway",
            name="alias",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="gateway",
            name="app_server_ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="Application Server IP"
            ),
        ),
        migrations.AddField(
            model_name="gateway",
            name="app_server_port",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Application Server Port"
            ),
        ),
        migrations.AddField(
            model_name="gateway",
            name="gateway_ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="Gateway IP"
            ),
        ),
        migrations.AddField(
            model_name="gateway",
            name="last_heartbeat",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gateway",
            name="last_successful_heartbeat",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gateway",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Logical name for the gateway",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="gateway",
            name="password",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="gateway",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="esltag",
            name="gateway",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tags",
                to="core.gateway",
            ),
        ),
        migrations.AlterField(
            model_name="gateway",
            name="estation_id",
            field=models.CharField(
                blank=True,
                max_length=4,
                null=True,
                unique=True,
                verbose_name="Gateway ID",
            ),
        ),
        migrations.AlterField(
            model_name="gateway",
            name="gateway_mac",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="MAC Address"
            ),
        ),
    ]
