# Generated by Django 5.1.5 on 2026-03-08 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_esltag_last_successful_gateway_id_gateway_alias_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gateway",
            name="is_active",
        ),
    ]
