# Generated by Django 5.1.5 on 2026-03-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_remove_gateway_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.TextField()),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="gateway",
            name="ap_version",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Firmware Version"
            ),
        ),
        migrations.AddField(
            model_name="gateway",
            name="free_space",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Free Space (MB)"
            ),
        ),
        migrations.AddField(
            model_name="gateway",
            name="heartbeat_interval",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Heartbeat Interval (sec)"
            ),
        ),
    ]
