# Generated by Django 5.1.5 on 2026-03-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_globalsetting_gateway_ap_version_gateway_free_space_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MQTTMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("sent", "Sent"), ("received", "Received")],
                        max_length=10,
                    ),
                ),
                (
                    "estation_id",
                    models.CharField(max_length=50, verbose_name="Gateway ID"),
                ),
                ("topic", models.CharField(max_length=255)),
                ("data", models.TextField(help_text="JSON payload")),
                ("is_success", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "MQTT Message",
                "verbose_name_plural": "MQTT Messages",
                "ordering": ["-timestamp"],
            },
        ),
    ]
