# Generated by Django 5.1.5 on 2026-03-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_mqttmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="gateway",
            name="is_encrypt_enabled",
            field=models.BooleanField(default=True, verbose_name="Encryption Enabled"),
        ),
    ]
