# Generated by Django 5.1.5 on 2026-03-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_gateway_is_encrypt_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="gateway",
            name="is_auto_ip",
            field=models.BooleanField(default=True, verbose_name="Auto IP (DHCP)"),
        ),
        migrations.AddField(
            model_name="gateway",
            name="local_ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="Static Local IP"
            ),
        ),
        migrations.AddField(
            model_name="gateway",
            name="netmask",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="Subnet Mask"
            ),
        ),
        migrations.AddField(
            model_name="gateway",
            name="network_gateway",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="Network Gateway"
            ),
        ),
    ]
