# Generated by Django 5.1.5 on 2026-03-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_gateway_is_auto_ip_gateway_local_ip_gateway_netmask_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gateway",
            name="ap_type",
            field=models.IntegerField(blank=True, null=True, verbose_name="AP Type"),
        ),
        migrations.AddField(
            model_name="gateway",
            name="disk_size",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Disk Size (MB)"
            ),
        ),
        migrations.AddField(
            model_name="gateway",
            name="module_version",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Module Version"
            ),
        ),
    ]
