# Generated by Django 5.1.5 on 2026-03-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_gateway_ap_type_gateway_disk_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gateway",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
