# Generated by Django 5.1.5 on 2026-03-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_gateway_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="esltag",
            name="last_pushed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last Pushed to Gateway"
            ),
        ),
    ]
