# Generated by Django 5.1.5 on 2026-03-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_esltag_last_pushed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="gateway",
            name="last_error_message",
            field=models.TextField(
                blank=True, null=True, verbose_name="Last Error Message"
            ),
        ),
        migrations.AddField(
            model_name="gateway",
            name="tags_comm_count",
            field=models.IntegerField(default=0, verbose_name="Tags in Communication"),
        ),
        migrations.AddField(
            model_name="gateway",
            name="tags_queued_count",
            field=models.IntegerField(default=0, verbose_name="Tags Queued"),
        ),
        migrations.AlterField(
            model_name="gateway",
            name="ap_version",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Base Station Version",
            ),
        ),
        migrations.AlterField(
            model_name="gateway",
            name="module_version",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Bluetooth Module Version",
            ),
        ),
    ]
