# Generated by Django 5.1.5 on 2026-03-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_gateway_last_error_message_gateway_tags_comm_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gateway",
            name="last_error_code",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Last Error Code"
            ),
        ),
        migrations.AddField(
            model_name="gateway",
            name="last_error_timestamp",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last Error Timestamp"
            ),
        ),
    ]
