# Generated by Django 5.1.5 on 2026-03-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_gateway_last_error_code_gateway_last_error_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gateway",
            name="is_online",
            field=models.CharField(
                choices=[
                    ("ONLINE", "Online"),
                    ("OFFLINE", "Offline"),
                    ("ERROR", "Error"),
                ],
                default="OFFLINE",
                max_length=10,
            ),
        ),
    ]
