# Generated by Django 5.1.5 on 2026-03-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_alter_gateway_is_online"),
    ]

    operations = [
        migrations.AddField(
            model_name="esltag",
            name="retry_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="esltag",
            name="sync_state",
            field=models.CharField(
                choices=[
                    ("IDLE", "No Pending Tasks"),
                    ("PROCESSING", "Generating Image..."),
                    ("IMAGE_READY", "Image Prepared"),
                    ("PUSHED", "Sent to Gateway"),
                    ("RETRY_WAITING", "Waiting for Retry"),
                    ("SUCCESS", "Update Confirmed"),
                    ("GEN_FAILED", "Image Generation Failed"),
                    ("PUSH_FAILED", "Gateway Delivery Failed"),
                    ("FAILED", "General Failure"),
                ],
                default="IDLE",
                max_length=20,
            ),
        ),
    ]
