# Generated by Django 5.1.14 on 2026-04-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_esltag_retry_count_alter_esltag_sync_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="esltag",
            name="tag_mac",
            field=models.CharField(
                db_index=True, max_length=50, verbose_name="Tag ID/MAC"
            ),
        ),
    ]
