# Generated by Django 5.1.14 on 2026-04-22 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_normalize_existing_macs"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(max_length=100, unique=True)),
                ("last_heartbeat", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("hostname", models.CharField(blank=True, max_length=255, null=True)),
                ("pid", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Service Status",
                "verbose_name_plural": "Service Statuses",
            },
        ),
    ]
